# Generated by Django 3.1.5 on 2021-05-11 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Democlass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('urls', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'democlass',
                'permissions': [('add-file', 'addfile')],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=30, null=True)),
                ('served_by', models.CharField(max_length=30, null=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(default='night-sky-wallpaper', null=True, upload_to='productspics/')),
                ('price', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(default='awesome', null=True)),
                ('reviews', models.TextField(default='awesome stuff', max_length=100, null=True)),
                ('tag', models.ManyToManyField(to='Leprechaun.tag')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('cheque', 'cheque'), ('cash', 'cash'), ('mpesa', 'mpesa'), ('card', 'card')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('Customer_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Items', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Leprechaun.products')),
                ('order_pay', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Leprechaun.orders')),
            ],
            options={
                'verbose_name': 'payments',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='prodct',
            field=models.ManyToManyField(to='Leprechaun.Products'),
        ),
    ]
