# Generated by Django 3.1.5 on 2021-03-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='pics')),
                ('name', models.CharField(help_text='Enter your name here', max_length=30)),
                ('address', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('town', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='profile_pics')),
                ('bio', models.TextField(help_text='bio here', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email here')),
                ('country', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
