# Generated by Django 3.1.5 on 2021-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customers_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
