# Generated by Django 3.1.5 on 2021-05-18 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('head_image', models.ImageField(upload_to='Blog_head_img')),
                ('article', models.TextField(max_length=600)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('article_urls', models.SlugField(blank=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readers_pics', models.ImageField(upload_to='reader_image')),
                ('email', models.EmailField(max_length=254)),
                ('date_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='author_image')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('article_writt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.articles')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
