# Generated by Django 3.1.5 on 2021-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='headline',
            field=models.TextField(max_length=50),
        ),
    ]
