# Generated by Django 3.1.5 on 2021-05-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20210518_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-pub_date'], 'verbose_name': 'articles'},
        ),
    ]
